### ISSUE TITLE
unstable_simd fails

### ISSUE THREAD

**Issue by Thell** [hasenbanck/romu#3]
`cargo test --features unstable-simd`

```
error[E0277]: cannot multiply `Simd<u64, 2>` by `{integer}`
   --> src/unstable_simd.rs:102:21
    |
102 |         self.x = zp * 0xD3833E804F4C574B;
    |                     ^ no implementation for `Simd<u64, 2> * {integer}`
```

for each of 128, 256 and 512.

```
active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.79.0-nightly (3c85e5624 2024-03-18)
```

**Comment by hasenbanck** [comment]
Oh, I guess you have now to splat the scalar values to all lanes. I will create a fix.

**Comment by hasenbanck** [comment]
I just pushed "v0.6.0", which should fix the unstable_simd feature on the current nightly release.

**Comment by Thell** [comment]
Wow, your response time was a quick a romuJr! Thanks.

Stable:
bytes/Rng/1048576       time:   [76.287 µs 76.449 µs 76.680 µs]
                        thrpt:  [12.736 GiB/s 12.774 GiB/s 12.801 GiB/s]
bytes/Rng128/1048576    time:   [256.27 µs 256.40 µs 256.53 µs]                                 
                        thrpt:  [3.8069 GiB/s 3.8087 GiB/s 3.8107 GiB/s]
bytes/Rng256/1048576    time:   [166.92 µs 167.25 µs 167.68 µs]                                 
                        thrpt:  [5.8240 GiB/s 5.8388 GiB/s 5.8506 GiB/s]
bytes/Rng512/1048576    time:   [111.04 µs 111.69 µs 112.46 µs]                                 
                        thrpt:  [8.6835 GiB/s 8.7435 GiB/s 8.7948 GiB/s]

Unstable:
bytes/Rng/1048576       time:   [76.081 µs 76.143 µs 76.210 µs]                              
                        thrpt:  [12.814 GiB/s 12.825 GiB/s 12.836 GiB/s]
bytes/Rng128/1048576    time:   [112.83 µs 112.92 µs 113.00 µs]                                 
                        thrpt:  [8.6421 GiB/s 8.6486 GiB/s 8.6550 GiB/s]
bytes/Rng256/1048576    time:   [71.401 µs 71.537 µs 71.753 µs]                                 
                        thrpt:  [13.610 GiB/s 13.651 GiB/s 13.677 GiB/s]
bytes/Rng512/1048576    time:   [68.964 µs 69.039 µs 69.119 µs]                                 
                        thrpt:  [14.129 GiB/s 14.145 GiB/s 14.161 GiB/s]

Nice gains.
